#**SERIE 02 - Solution**

##**EXO01**

In [125]:
x_attitude = [6,9,8,3,10,4,5,2,11,9,10,2]
y_duree = [10,12,12,4,12,6,8,2,18,9,17,2]
z_importance = [3,11,4,1,11,1,7,4,8,10,8,5]

In [126]:
import math
import pandas as pd

In [127]:
def corr_lin_test_t(x , y):
  moy_x = sum(x)/len(y)
  moy_y = sum(y)/len(y)
  cov_xy = sum((a - moy_x)*(b - moy_y) for (a,b) in zip(x , y))/ len(x)
  etX = (sum((a - moy_x)**2 for a in x)/len(x))**0.5
  etY = (sum((b - moy_y)**2 for b in y)/len(y))**0.5
  r = round(cov_xy/(etX*etY),3)
  sr = math.sqrt((1-r**2)/(len(x)-2))
  t = round((abs(r))/sr,3)
  ddl = len(x)-2
  return('Corrélation linéaire est : ' ,r , 'La valeur de t est : ' ,t , 'DDL = ' ,ddl ,'alpha = 0.05')

Calculer Correlation Lineaire entre les VAR

In [128]:
corr_lin_test_t(x_attitude , y_duree)

('Corrélation linéaire est : ',
 0.936,
 'La valeur de t est : ',
 8.409,
 'DDL = ',
 10,
 'alpha = 0.05')

In [129]:
corr_lin_test_t(x_attitude , z_importance)

('Corrélation linéaire est : ',
 0.733,
 'La valeur de t est : ',
 3.408,
 'DDL = ',
 10,
 'alpha = 0.05')

In [130]:
corr_lin_test_t(z_importance , y_duree)

('Corrélation linéaire est : ',
 0.55,
 'La valeur de t est : ',
 2.083,
 'DDL = ',
 10,
 'alpha = 0.05')

On a t(seuil)=1.8125 donc on a : 

1- t > t(seuil) , donc rejet de H0 , l'existence d'une relation linéaire significatif .

2- t > t(seuil) , donc rejet de H0 , l'existence d'une relation linéaire significatif .

3- t > t(seuil) , donc rejet de H0 , l'existence d'une relation linéaire significatif

##**EXO02**

In [131]:
df = pd.read_excel('/content/add1.xlsx')
df.head(13)

    Années  Ventes  Depenses  Prix  part_marche  taille  satisfaction
0        1   23000      5000    25         8.30      15             3
1        2   22500      8000    25         7.80      15             3
2        3   36000     12000    35        12.40      24             4
3        4   42000     12000    18        13.00      24             4
4        5   34000     10000    16         9.70      22             5
5        6   27000      9000    10         8.66      22             4
6        7   48000     14000    28        13.60      28             4
7        8   38000     11000    28        10.20      25             5
8        9   18000      6000    12         7.10      25             3
9       10   28500     10000    16         7.50      25             3
10      11   35000     11000    22         8.70      18             2
11      12   18000      4000    15         5.80      16             1

In [132]:
import numpy as np
matrix = df.corr()
matrix

,Années,Ventes,Depenses,Prix,part_marche,taille,satisfaction
Années,1.000000,-0.108143,-0.082531,-0.411871,-0.392110,0.183686,-0.465516
Ventes,-0.108143,1.000000,0.935948,0.478889,0.911358,0.607911,0.586639
Depenses,-0.082531,0.935948,1.000000,0.441299,0.847801,0.671478,0.596247
Prix,-0.411871,0.478889,0.441299,1.000000,0.553459,0.049165,0.236732
part_marche,-0.392110,0.911358,0.847801,0.553459,1.000000,0.590250,0.638240
taille,0.183686,0.607911,0.671478,0.049165,0.590250,1.000000,0.596440
satisfaction,-0.465516,0.586639,0.596247,0.236732,0.638240,0.596440,1.000000

In [133]:
sr_value = []
t_value = []

for i in matrix.values.reshape(-1):
  if i == 1 :
    pass
  else:
    sr_value.append(math.sqrt((1-i**2)/10))
    t_value.append(((abs(i))/math.sqrt((1-i**2)/10)))

In [134]:
len(sr_value)

42

In [135]:
data ={'Sr' : sr_value,'T' : t_value}
df_st = pd.DataFrame(data)

In [136]:
var_c =[]
for i in matrix.index:
  for j in matrix.index:
    if i == j:
      pass
    else:
      var_c.append((i,j))

In [137]:
len(var_c)

42

In [138]:
df_st['variables_de_liaison'] = var_c

In [139]:
t_seuil = 1.8125
interp = []
for i in df_st['T']:
  if abs(i) >= t_seuil:
    interp.append('Rejet H0 , liaison linéaire significatif')
  else:
    interp.append('Non rejet de H0 , pas de liaison linéaire')

In [140]:
len(interp)

42

In [141]:
df_st['Interpretation'] = interp

In [142]:
df_st

,Sr,T,variables_de_liaison,Interpretation
0,0.314373,0.343994,"(Années, Ventes)","Non rejet de H0 , pas de liaison linéaire"
1,0.315149,0.261879,"(Années, Depenses)","Non rejet de H0 , pas de liaison linéaire"
2,0.288160,1.429312,"(Années, Prix)","Non rejet de H0 , pas de liaison linéaire"
3,0.290904,1.347902,"(Années, part_marche)","Non rejet de H0 , pas de liaison linéaire"
4,0.310847,0.590920,"(Années, taille)","Non rejet de H0 , pas de liaison linéaire"
5,0.279874,1.663305,"(Années, satisfaction)","Non rejet de H0 , pas de liaison linéaire"
6,0.314373,0.343994,"(Ventes, Années)","Non rejet de H0 , pas de liaison linéaire"
7,0.111356,8.404983,"(Ventes, Depenses)","Rejet H0 , liaison linéaire significatif"
8,0.277609,1.725051,"(Ventes, Prix)","Non rejet de H0 , pas de liaison linéaire"
9,0.130164,7.001617,"(Ventes, part_marche)","Rejet H0 , liaison linéaire significatif"
10,0.251086,2.421125,"(Ventes, taille)","Rejet H0 , liaison linéaire significatif"
11,0.256097,2.290695,"(Ventes, satisfaction)","Rejet H0 , liaison linéaire significatif"
12,0.315149,0.261879,"(Depenses, Années)","Non rejet de H0 , pas de liaison linéaire"
13,0.111356,8.404983,"(Depenses, Ventes)","Rejet H0 , liaison linéaire significatif"
14,0.283770,1.555126,"(Depenses, Prix)","Non rejet de H0 , pas de liaison linéaire"
15,0.167700,5.055450,"(Depenses, part_marche)","Rejet H0 , liaison linéaire significatif"
16,0.234333,2.865489,"(Depenses, taille)","Rejet H0 , liaison linéaire significatif"
17,0.253868,2.348649,"(Depenses, satisfaction)","Rejet H0 , liaison linéaire significatif"
18,0.288160,1.429312,"(Prix, Années)","Non rejet de H0 , pas de liaison linéaire"
19,0.277609,1.725051,"(Prix, Ventes)","Non rejet de H0 , pas de liaison linéaire"
20,0.283770,1.555126,"(Prix, Depenses)","Non rejet de H0 , pas de liaison linéaire"
21,0.263379,2.101379,"(Prix, part_marche)","Rejet H0 , liaison linéaire significatif"
22,0.315845,0.155663,"(Prix, taille)","Non rejet de H0 , pas de liaison linéaire"
23,0.307239,0.770515,"(Prix, satisfaction)","Non rejet de H0 , pas de liaison linéaire"
24,0.290904,1.347902,"(part_marche, Années)","Non rejet de H0 , pas de liaison linéaire"
25,0.130164,7.001617,"(part_marche, Ventes)","Rejet H0 , liaison linéaire significatif"
26,0.167700,5.055450,"(part_marche, Depenses)","Rejet H0 , liaison linéaire significatif"
27,0.263379,2.101379,"(part_marche, Prix)","Rejet H0 , liaison linéaire significatif"
28,0.255265,2.312300,"(part_marche, taille)","Rejet H0 , liaison linéaire significatif"
29,0.243444,2.621715,"(part_marche, satisfaction)","Rejet H0 , liaison linéaire significatif"
30,0.310847,0.590920,"(taille, Années)","Non rejet de H0 , pas de liaison linéaire"
31,0.251086,2.421125,"(taille, Ventes)","Rejet H0 , liaison linéaire significatif"
32,0.234333,2.865489,"(taille, Depenses)","Rejet H0 , liaison linéaire significatif"
33,0.315845,0.155663,"(taille, Prix)","Non rejet de H0 , pas de liaison linéaire"
34,0.255265,2.312300,"(taille, part_marche)","Rejet H0 , liaison linéaire significatif"
35,0.253823,2.349830,"(taille, satisfaction)","Rejet H0 , liaison linéaire significatif"
36,0.279874,1.663305,"(satisfaction, Années)","Non rejet de H0 , pas de liaison linéaire"
37,0.256097,2.290695,"(satisfaction, Ventes)","Rejet H0 , liaison linéaire significatif"
38,0.253868,2.348649,"(satisfaction, Depenses)","Rejet H0 , liaison linéaire significatif"
39,0.307239,0.770515,"(satisfaction, Prix)","Non rejet de H0 , pas de liaison linéaire"
40,0.243444,2.621715,"(satisfaction, part_marche)","Rejet H0 , liaison linéaire significatif"
41,0.253823,2.349830,"(satisfaction, taille)","Rejet H0 , liaison linéaire significatif"